version: '3.8'

services:
  redis:
    image: redis:7.4
    container_name: redis-session-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: redis-session-app
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
